// "use client";

import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "~/components/core/Navbar";
// import Footer from "~/components/core/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// import { userContext } from "~/supports/context/useUserContext";
// import { cartContext } from "~/supports/context/useCartContext";
// import { useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Clone Depop Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const [userData, setUserData] = useState(null);
  // const [userCart, setUserCart] = useState(null);
  return (
    <html lang="en">
      {/* <userContext.Provider value={{ userData, setUserData }}>
        <cartContext.Provider value={{ userCart, setUserCart }}> */}
          <body className={inter.className}>
            {/* <Navbar /> */}
            <ToastContainer />
            {children}
            {/* <Footer /> */}
          </body>
        {/* </cartContext.Provider>
      </userContext.Provider> */}
    </html>
  );
}
